#!/usr/bin/env bash
#World wide web

if [ "$#" -eq 1 ]; then
	domain=$1
	echo "$(dig www.$domain | awk '/ANSWER SECTION:/ {getline; print "The subdomain www is a "$4" record and points to "$5}')"
	echo "$(dig lb-01.$domain | awk '/ANSWER SECTION:/ {getline; print "The subdomain lb-01 is a "$4" record and points to "$5}')"
	echo "$(dig web-01.$domain | awk '/ANSWER SECTION:/ {getline; print "The subdomain web-01 is a "$4" record and points to "$5}')"
	echo "$(dig web-02.$domain | awk '/ANSWER SECTION:/ {getline; print "The subdomain web-02 is a "$4" record and points to "$5}')"
elif [ "$#" -eq 2 ]; then
	domain=$1
	subdomain=$2
	echo "$(dig $subdomain.$domain | awk '/ANSWER SECTION:/ {getline; print "The subdomain '"$subdomain"' is a "$4" record and points to "$5}')"
fi
