#!/usr/bin/env bash
#Transfer a file to your server

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

FILE_PATH=$1
IP_ADD=$2
USERNAME=$3
SSH_KEY=$4
scp -i "$SSH_KEY" -o stricthostkeychecking=no "$FILE_PATH" "$USERNAME@$IP_ADD:~/"
