#!/usr/bin/env bash
#Not found page 404

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
site_re="https://www.youtube.com/watch?v=QH2-TGUlwu4"
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me $site_re permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/my_404.html
sudo sed -i "/listen 80 default_server/a error_page 404 /my_404.html; location = /my_404.html {root /usr/share/nginx/html;\n internal;}" /etc/nginx/sites-available/default
sudo service nginx restart
